# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0002_auto_20161119_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='feed_img/ru/')),
                ('info', redactor.fields.RedactorField(blank=True, verbose_name='Text')),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoyalBread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='feed_img/ru/')),
                ('info', redactor.fields.RedactorField(blank=True, verbose_name='Text')),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
