# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('feed_image', models.ImageField(upload_to='feed_img/en/')),
                ('feed_info', models.TextField()),
            ],
        ),
    ]
