# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='feed_img/ru/')),
                ('info', redactor.fields.RedactorField(verbose_name='Text')),
            ],
        ),
        migrations.AlterField(
            model_name='feedproducts',
            name='feed_image',
            field=models.ImageField(upload_to='feed_img/ru/'),
        ),
        migrations.AlterField(
            model_name='feedproducts',
            name='feed_info',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
